### ISSUE TITLE
issues importing this project (NixOS)

### ISSUE THREAD

**Issue by tycho01** [tensorflow/haskell#199]
I've tried a few ways if I could use TensorFlow Haskell, but haven't gotten it to work yet so far.
What I've tried:
- import from Hackage: ran into #180
- Docker: I'm not sure how this'd work. Would I extend the Dockerfile so as to have it include my own code?
- adding this to `extra-deps`:
```
- github: tensorflow/haskell
  commit: e40d2c44f0a861701cc90ec73c2bcee669ab5ba7
```
Somehow yielded:
```
Archive extraction failed. Tarballs and zip archives are supported, couldn't handle the following URL, https://github.com/tensorflow/haskell/archive/e40d2c44f0a861701cc90ec73c2bcee669ab5ba7.tar.gz downloaded to the file dNWbt9ZMvX9a.http-archive
```
- run from local copy:
`stack.yaml`:
```
flags: {}
extra-package-dbs: []
packages:
- .
- location: /home/tycho/Desktop/haskell
  extra-dep: true
  subdirs:
    - tensorflow
    - tensorflow-proto
    - tensorflow-opgen 
    - tensorflow-ops
    - tensorflow-core-ops
extra-deps: []
# TensorFlow:
- haskell-src-exts-1.19.1
- proto-lens-protoc-0.2.2.3
- proto-lens-protobuf-types-0.2.2.0
- snappy-framing-0.1.1
- snappy-0.2.0.2
resolver: lts-11.15
explicit-setup-deps:
  "*": true
nix:
  enable: true
  packages: [zlib.dev, zlib.out, snappy, python36Packages.tensorflow, python36Packages.tensorflowWithoutCuda]
```
Then running `stack build` yielded:
```
   Process exited with code: ExitFailure 1
    Logs have been written to: /run/media/tycho/Drogon/Coding/ml/reinforcement-learning/gym-http-api/binding-hs/.stack-work/logs/tensorflow-0.1.0.2.log

    Configuring tensorflow-0.1.0.2...
    Cabal-simple_mPHDZzAJ_2.0.1.0_ghc-8.2.2: Missing dependency on a foreign
    library:
    * Missing C library: tensorflow
    This problem can usually be solved by installing the system package that
    provides this library (you may need the "-dev" version). If the library is
    already installed but in a non-standard location then you can use the flags
    --extra-include-dirs= and --extra-lib-dirs= to specify where it is.
```
(was `python36Packages.tensorflow` not correct here?)
- Nix: `stack --nix build` runs successfully, though not sure how to proceed from there. Importing this `shell.nix` file into `environment.systemPackages` yielded me `The option value 'environment.systemPackages.[definition 8-entry 25]' in '/etc/nixos/profiles/development/haskell.nix' is not of type 'package'`.

I apologize for my inexperience -- hopefully part of these may be easier to resolve.
