### ISSUE TITLE
Stack install - Symbolic link dest not found...

### ISSUE THREAD

**Issue by Cmdv** [tensorflow/haskell#263]
Trying to use tensorflow as part of a project but getting stumped when using stack.

stack 2.3.1 x86_64 hpack-0.34.2
ghc 8.8.3

running `stack install` I get the following error:
```
Cloning 8cde4d6a277f188ca495d29096a62b36e8534a3f from https://github.com/tensorflow/haskell.git
Unsupported tarball from /private/var/folders/gp/s6jjtfpd2lb5fdnq4b6vqq8m0000gn/T/with-repo-archive67964/foo.tar: Symbolic link dest not found from tensorflow-opgen/third_party to ../third_party/tensorflow, looking for third_party/tensorflow.
This may indicate that the source is a git archive which uses git-annex.
See https://github.com/commercialhaskell/stack/issues/4579 for further information.
```

here is my setup

`stack.yaml`:

```
resolver: lts-15.11
packages:
- .
extra-deps:
  - git: https://github.com/tensorflow/haskell.git
    commit: 8cde4d6a277f188ca495d29096a62b36e8534a3f
    subdirs:
    - tensorflow
    - tensorflow-core-ops
    - tensorflow-logging
    - tensorflow-opgen
    - tensorflow-ops
    - tensorflow-proto
    - tensorflow-mnist
    - tensorflow-mnist-input-data
    - tensorflow-records
    - tensorflow-records-conduit
    - tensorflow-test
  - proto-lens-protobuf-types-0.2.1.0
  - snappy-0.2.0.2
  - snappy-framing-0.1.2
  - tensorflow-logging-0.1.0.0
  - tensorflow-records-0.1.0.0
  - tensorflow-records-conduit-0.1.0.0

extra-lib-dirs:
    - /usr/local/lib
extra-include-dirs:
    - /usr/local/include
```

`package.yaml`:

```
name:                Haskell-image-recognition
version:             0.1.0.0
github:              "githubuser/Haskell-image-recognition"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/githubuser/Haskell-image-recognition#readme>

dependencies:
- base >= 4.7 && < 5
- tensorflow
- tensorflow-opgen
- tensorflow-ops
- tensorflow-logging
- tensorflow-mnist
- proto-lens

library:
  source-dirs: src

executables:
  Haskell-image-recognition-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-image-recognition

tests:
  Haskell-image-recognition-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Haskell-image-recognition
```

I tried taking a look at `https://github.com/commercialhaskell/stack/issues/4579` but couldn't work out how it relates or can be fixed. :)

If more information is required please let me know.
